repos:
  vxsuite:
    version: main
virt_image_path: "/var/lib/libvirt/images"
vm_name: "debian-12.2"
vm_disk_size_gb: 110
iso_version: "12.2.0"
iso_name: "debian-{{ iso_version }}-amd64-netinst.iso"
iso_url: "https://cdimage.debian.org/cdimage/archive/{{ iso_version }}/amd64/iso-cd"
vm_preseed_path: "/home/{{ ansible_env.SUDO_USER }}/code/vxsuite-build-system/preseeds"
vm_preseed_file: "production-preseed.cfg"
secure_boot: true
vm_clone_name: "deb12"
rust_version: "1.93.0"
